Use the following code for the questions below:

In [1]:
import numpy as np
import math as m

In [90]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?

How many positive numbers are there?

How many even positive numbers are there?

In [91]:
a[a < 0]

a[a < 0].shape

(4,)

In [4]:
a[a > 0]

a[a > 0].shape

(5,)

In [5]:
a[(a % 2 == 0) & (a > 0)]

a[(a % 2 == 0) & (a > 0)].shape

(3,)

If you were to add 3 to each data point, how many positive numbers would there be?

In [6]:
ap = a + 3

ap[ap > 0].shape

(10,)

If you squared each number, what would the new mean and standard deviation be?



In [7]:
a.mean(), a.std()

(3.0, 8.06225774829855)

In [8]:
asq = a ** 2
asq

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [9]:
asq.mean(), asq.std()

(74.0, 144.0243035046516)

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.



In [10]:
ac = a - a.mean()
ac

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

Calculate the z-score for each data point. Recall that the z-score is given by:

x - mean / std

In [11]:
a_zscore = (a - a.mean()) / a.std()

a_zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [12]:
import numpy as np
# Life w/o numpy to life with numpy

In [96]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Use python's built in functionality/operators to determine the following:


- Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [14]:
sum_of_a = sum(a)

sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [15]:
min_of_a = min(a)

min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [16]:
max_of_a = max(a)

max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [17]:
mean_of_a = sum(a) / len(a) 

mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [18]:
#returns each number multiplied by itself
product = 1

for x in a:
    
    product = product * x
    
    print(product)

1
2
6
24
120
720
5040
40320
362880
3628800


In [19]:
#multiplies each number together
m.prod(a)

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [98]:
squares_of_a = aa ** 2

squares_of_a

NameError: name 'aa' is not defined

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [ ]:
for x in a:
    
    if x % 2 == 1:
        
        print(x)
        

In [ ]:
odds_in_a = aa[aa % 2 == 1]

odds_in_a


Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [104]:
evens_in_a = aa[aa % 2 == 0]

evens_in_a


array([ 2,  4,  6,  8, 10])

In [103]:
aa = np.array(a)

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [105]:
b = [
    [3, 4, 5],
    [6, 7, 8]
     ]

In [106]:
 ba = np.array(b)

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [109]:
sum_of_b = ba.sum()

np.sum(sum_of_b)
    

33

Exercise 2 - refactor the following to use numpy. 


In [ ]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

min_of_b

In [110]:
min_of_ba = ba.min()

min_of_ba

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [ ]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

In [111]:
max_of_ba = ba.max()

max_of_ba

8

Exercise 4 - refactor the following using numpy to find the mean of b


In [ ]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


In [112]:
mean_of_ba = ba.mean()

mean_of_ba

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [ ]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b

In [113]:
product_of_ba = ba.prod()

product_of_ba

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 


In [ ]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b

In [114]:
squares_of_ba = ba ** 2

squares_of_ba

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b


In [ ]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds_in_b

In [115]:
odds_in_ba = ba[ba % 2 == 1]

odds_in_ba

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [ ]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_b

In [116]:
evens_in_ba = ba[ba % 2 == 0]

evens_in_ba

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.


In [117]:
ba.shape

(2, 3)

Exercise 10 - transpose the array b.


In [86]:
np.transpose(ba)

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [88]:
ba.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [ ]:
ba.reshape(6, 1)

Setup 3

In [118]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.


In [119]:
ca = np.array(c)

ca

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 1 - Find the min, max, sum, and product of c.


In [120]:
ca.min(), ca.max(), ca.sum(), ca.prod()

(1, 9, 45, 362880)

Exercise 2 - Determine the standard deviation of c.


In [27]:
ca.std()

2.581988897471611

Exercise 3 - Determine the variance of c.


In [28]:
ca.var()

6.666666666666667

Exercise 4 - Print out the shape of the array c


In [29]:
ca.shape

(3, 3)

Exercise 5 - Transpose c and print out transposed result.


In [54]:
transpose_c = np.transpose(c)
transpose_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c. 


In [51]:
ca.dot(ca, ca)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [50]:
cat = transpose_c * ca
np.sum(cat)

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [58]:
ca_transposed_prod = np.product(cat)

print(ca_transposed_prod)

131681894400


Setup 4


In [64]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [70]:
da = np.array(d)

da

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

Exercise 1 - Find the sine of all the numbers in d


In [60]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d


In [61]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d


In [68]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d


In [121]:
de = da[da < 0]

de

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d


In [122]:
dp = da[da >= 0]

dp

array([ 90,  30,  45,   0, 120, 180,  45, 270,  90,   0,  60,  45,  90,
       180])

Exercise 6 - Return an array of only the unique numbers in d.


In [99]:
np.unique(da)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.


In [102]:
len(np.unique(da))

11

Exercise 8 - Print out the shape of d.


In [76]:
da.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.


In [79]:
npt = np.transpose(da)
    
npt.shape   

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [81]:
da.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])